# Generated by Django 3.2.4 on 2021-08-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0003_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clickbait',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
    ]
