# Generated by Django 3.2.4 on 2021-08-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0004_auto_20210825_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
