# Generated by Django 3.2.4 on 2021-08-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0005_rename_firts_name_author_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='firts_name',
        ),
    ]
