# Generated by Django 3.2.4 on 2021-10-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0012_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=15)),
                ('readLater', models.ManyToManyField(null=True, to='blog_posts.post')),
            ],
        ),
    ]
