# Generated by Django 3.2.4 on 2021-10-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0013_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='readLater',
            field=models.ManyToManyField(to='blog_posts.post'),
        ),
    ]
