# Generated by Django 3.2.4 on 2021-10-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0017_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isSuperUser',
        ),
    ]
