# Generated by Django 3.2.4 on 2021-10-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0018_remove_user_issuperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isSuperUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
